[package]
name = "martini-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "RTIN mesh generation for terrain data based on the Martini algorithm"

[lib]
name = "martini"

[dependencies]

[dev-dependencies]
approx = "0.5"
image = "0.25"
