[workspace]
members = ["martini", "quantized-mesh", "terrain-codec", "wasmbench"]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/reearth/terrain-codec"

[workspace.dependencies]
flate2 = "1"
serde = "1"
serde_json = "1"
